# -*- coding: utf-8 -*-
"""Programa Organização Financeira.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYzdNYI9qohRYT-GBFRUvzw_lpI-XV4U
"""

# criação de variáveis
saldo = 0
total_receitas = 0
total_despesas = 0

# criação do dicionário

historico = {}

# def da função de receita ou despesa

def add_historico(tipo_movimentacao, operacao, saldo, total):
  while True:
      nome = input(f"""Qual o nome da {tipo_movimentacao}? """)
      valor = float(input(f"""Qual o valor da {tipo_movimentacao}? """))

      if valor <=0:
        print("""Entrada inválida!""")
      else:
        historico[nome] = operacao * valor
        saldo = saldo + (operacao)*valor
        total = total + valor
        while True:
          resposta = input(f"""
            Deseja adicionar mais alguma {tipo_movimentacao}?
            1 - Sim
            2 - Não
            """)
          if resposta == '2':
            return saldo, total
          elif resposta == '1':
            break

          elif resposta != '1' and resposta != '2':
            print("""Entrada inválida!""")


menu_principal = """
==============================
      SISTEMA FINANCEIRO
==============================

1 - Adicionar receita
2 - Adicionar despesa
3 - Mostrar saldo
4 - Mostrar histórico
5 - Sair

"""

#
while True:
  opcao_menu = input(menu_principal)

  if opcao_menu == '1':
    saldo, total_receitas = add_historico('receita', 1, saldo, total_receitas)

  elif opcao_menu == '2':
    saldo, total_despesas = add_historico('despesa', -1, saldo, total_despesas)

  elif opcao_menu == '3':
    while True:
      print(f'Seu saldo atual é: R$ {saldo:.2f}')

      if saldo < 0:
        print('Seu saldo está NEGATIVO!')

      elif  0 < saldo < 300:
        print('Atenção! Seu saldo está baixo!')

      elif 300 < saldo < 500:
        print('Você está em pleno controle das suas finanças! Parabéns!')

      elif 500 < saldo:
        print('Você está com muito dinheiro em saldo! :)')

      voltar_menu = input("""Para voltar para o Menu Principal digite '1' """)
      if voltar_menu == '1':
        break
      else:
        print("""Entrada inválida!""")
        break

  elif opcao_menu == '4':
    while True:
      print('Histórico de movimentações: ')

      for nome_receita in historico.items():
        print(nome_receita)

      print(f'Seu total de receitas foi de: {total_receitas}')
      print(f'Seu total de despesas foi de: {total_despesas}')

      voltar_menu = input("""Para voltar para o Menu Principal digite '1' """)
      if voltar_menu == '1':
        break

  elif opcao_menu == '5':
    break

  else:
    print("""Entrada inválida!""")

